app = "dance-cxhveq"
primary_region = "cdg"

[env]
PORT = "8080"

[http_service]
auto_start_machines = true
force_https = true
internal_port = 8_084
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
memory_mb = 1_024
